import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";


const bronz=localFont({
  src:[
    {
      path:"../public/fonts/bronz/Bronz.ttf",
style:"normal"

    }
  ]
  ,  
  variable: '--font-bronz'

})

const corbel=localFont({
  src:[
   
    {
      path:"../public/fonts/corbel/CorbelItalic.ttf",
      

    },
    {
      path:"../public/fonts/corbel/corbelz.ttf",
     

    },
    {
      path:"../public/fonts/corbel/CorbelBold.ttf",
      style:"bold"
    }
  ]
  ,  
  variable: '--font-corbel'

})


export const metadata: Metadata = {
  title: "Ozuna",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  className={`${corbel.className}`} suppressHydrationWarning>
      <body
        className={`${corbel.variable}  ${bronz.variable}   antialiased`}
      >

        <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
      </body>
    </html>
  );
}
